@echo off
echo Stopping existing Flask API processes...
taskkill /f /im python.exe 2>nul

echo Waiting 2 seconds...
timeout /t 2 /nobreak > nul

echo Starting Flask API with new configuration...
cd FlaskAPI\src
start "Flask API" cmd /k "python app.py"

echo Flask API is starting with host=0.0.0.0 and CORS enabled for your IP...
echo.
echo Press any key to exit...
pause > nul
